name: beariscope
description: "FRC strategy data viewer developed by Bear Metal, team 2046"
version: 26.5.0+20
resolution: workspace
publish_to: none

environment:
  sdk: ^3.13.0
  flutter: ^3.0.0

dependencies:
  core:
    path: ../../packages/core
  crop_your_image: ^2.0.0
  cupertino_icons: ^1.0.9
  file_picker: ^12.1.2
  syncfusion_flutter_charts: ^34.2.5
  syncfusion_flutter_core: ^34.2.5
  syncfusion_flutter_sliders: ^34.2.5
  flutter:
    sdk: flutter
  flutter_riverpod: 3.3.2
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.3.0
  flutter_web_plugins:
    sdk: flutter
  go_router: ^18.0.0
  excel: ^4.0.6
  qr_flutter: ^4.1.0
  logger: ^2.7.0
  lucide_icons_flutter: ^3.1.17
  package_info_plus: ^10.2.1
  provider: ^6.1.5+1
  riverpod_annotation: 4.0.3
  services:
    path: ../../packages/services
  shared_preferences: ^2.5.5
  share_plus: ^13.3.0
  http: ^1.6.0
  simple_icons: ^16.23.0
  ui:
    path: ../../packages/ui
  url_launcher: ^6.3.2
  window_size: ^0.2.0
  hive_ce_flutter: ^2.3.4
  image: 4.3.0
  google_fonts: ^8.2.1
  animations: ^3.0.0
  dots_indicator: ^4.0.1
  intl: ^0.20.3
  mime: ^2.1.0
  internet_connection_checker_plus: ^3.1.1
  path_provider: ^2.1.6
  flutter_animate: ^4.5.2
  flex_color_picker: ^4.0.0
  material_ui: ^1.1.0
  cupertino_ui: ^1.0.1
  stupid_simple_sheet: ^0.9.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: 4.0.4
  build_runner: 2.15.1
  riverpod_lint: 3.1.4
  flutter_launcher_icons: ^0.14.4

flutter:
  config:
    enable-swift-package-manager: true
  uses-material-design: true
  assets:
    - path: assets/
    - path: assets/icon/ios_previews/
      platforms: [ ios ]
  fonts:
    - family: Xolonium
      fonts:
        - asset: assets/fonts/Xolonium-Regular.ttf
          weight: 400
        - asset: assets/fonts/Xolonium-Bold.ttf
          weight: 700
